### ISSUE TITLE
No such module 'ReachabilitySwift

### ISSUE THREAD

**Issue by mohamamdkalim** [ashleymills/Reachability.swift#257]
Hello,

i am using xcode 9.1 and swift 3.2 always getting an error:

No such module 'ReachabilitySwift

in podfile:
  pod 'ReachabilitySwift'

kindly let me know what can i do ... always getting an error

**Comment by eoinzy** [comment]
Its been renamed to just "Reachability".
Change the name in your Podfile and try again.

**Comment by NiltiakSivad** [comment]
I think @eoinzy is installing the wrong library if he is updating the Podfile to be "Reachability". It should definitely be `pod 'ReachabilitySwift'` in your Podfile. However, the import statement, should indeed be `import Reachability`. 

Reference the CocoaPods installation steps in the documentation: https://github.com/ashleymills/Reachability.swift#cocoapods-1

If you're still getting errors after doing the above. I think this is a bug in xCode. I was getting a similar error running xCode 9.1 and Swift 4.0.2.

What I did to resolve: 
1. Clean project 
2. Close xCode
3. Open xCode
4. Rebuild project

After these steps, in xCode 9.1 the `No such module`  error would still appear, but my build would succeed, and my references to `ReachabilitySwift` classes resolved fine, so I ignored the error, and continued coding. 

I also tested on xCode 9.0 and the error was not reproducible there, it only appeared in xCode 9.1.

**Comment by 547** [comment]
You just get into this directory: targets -> build settings -> linking -> other linker flags.  Then, you can just replace the ReachabilitySwift with the Reachability.

**Comment by jobinsjohn** [comment]
@NiltiakSivad The issue is still happening after following your steps also.

**Comment by thirumaleshios** [comment]
@NiltiakSivad @547 @jobinsjohn The issue is resolved with " import ReachabilitySwift "

**Comment by frankbfromh** [comment]
I ran into the same problem as described above. Turns out there were different deployment targets across the various targets. I set them all to the same version and the problem was solved.

**Comment by paulshapiro** [comment]
I believe this issue is caused by CocoaPods inserting an Other Linker Flag of `-framework ReachabilitySwift` due to the CocoaPod name of the module. Isn't that expected behavior and therefore the CocoaPod spec name is wrong, since the framework module is now called Reachability? i.e. even if we modified Other Linker Flags to "Reachability" to get it compiling, it's not a fix; CocoaPods will just generate the same thing again.

**Comment by paulshapiro** [comment]
Just a little more info on this. Carthage instructions cite a "ReachabilitySwift.framework" but CocoaPods is most definitely producing a "Reachability.framework"

**Comment by Allan-Nava** [comment]
@NiltiakSivad , I use your steps but I still have the same error:

<img width="723" alt="schermata 2018-02-08 alle 08 22 29" src="https://user-images.githubusercontent.com/22498435/35960241-39e4e4d0-0ca9-11e8-9d98-046d0539a0ee.png">
<img width="271" alt="schermata 2018-02-08 alle 08 22 42" src="https://user-images.githubusercontent.com/22498435/35960250-422b33ba-0ca9-11e8-99b0-617330d38314.png">


<img width="441" alt="schermata 2018-02-08 alle 08 23 00" src="https://user-images.githubusercontent.com/22498435/35960255-4afe8780-0ca9-11e8-9931-c5278d408df9.png">

**Comment by hollywoodno** [comment]
Issue still exists for me. I decided to use the other option which is just to drop the Realibility.swift file into my project.

**Comment by kamifernandez** [comment]
i solve with import Reachability

**Comment by hamchapman** [comment]
As many have stated you should be using `import Reachability` 👍

**Comment by jayjohnchiong** [comment]
It's still giving No such module 'Reachability'

**Comment by zilions** [comment]
I'm getting the same error as @mirkin. Able to test fine in the simulators, although when trying to archive the error is displayed.

**Comment by georgenimber** [comment]
I am having a similar issue with an app crash (symbol not found)
The app has both objective C Reachability and the Swift ReachabilitySwift.
Now that the ReachabilitySwift was renamed ,will I have an issue with both included ?
